### ISSUE TITLE
Warnings prevent fold from throwing out errors

### ISSUE THREAD

**Issue by Gozala** [Gozala/reducible#3]
The problem with current implementation is that  `reduce` functions catches error and then passes it back to `next` if it throws again error is thrown out. If pipeline consists of multiple reduce then error is catch by later `reduce` and it no longer is thrown out.

Not quite understand what exactly is going on but following code illustrates an issues:

``` js
> fold(Error("!"), noop)
Error: !
    at Error (unknown source)
    at repl:1:7
    at REPLServer.self.eval (repl.js:111:21)
    at Interface.<anonymous> (repl.js:250:12)
    at Interface.EventEmitter.emit (events.js:93:17)
    at Interface._onLine (readline.js:199:10)
    at Interface._line (readline.js:517:8)
    at Interface._ttyWrite (readline.js:735:14)
    at ReadStream.onkeypress (readline.js:98:10)
    at ReadStream.EventEmitter.emit (events.js:123:20)
    at emitKey (readline.js:1057:12)
    at ReadStream.onData (readline.js:806:7)
> fold(map(Error("!"), True), noop)
Source attempted to send item after it ended { reduce: [Function: reduceReducer] } [Error: !]
[Error: !]
```

**Comment by Gozala** [comment]
Ok so what happens is that thrown error is caught by reduce and is passed back down the flow. If another is `reduce` is down the pipe error causes input to be marked as errored and all the followup values are logged in warnings but ignored. That prevents errors to be thrown out and instead they are logged as warnings.
